// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pam.Ingest.Data;

#nullable disable

namespace Pam.Ingest.Data.Migrations
{
    [DbContext(typeof(IngestDbContext))]
    [Migration("20260512225829_InitialIngest")]
    partial class InitialIngest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ingest")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pam.Ingest.Transactions.Models.VendorTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("created_by_type");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("LastModifiedByType")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("last_modified_by_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("rejected_reason");

                    b.Property<string>("RoundId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("round_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorReference")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("vendor_reference");

                    b.HasKey("Id")
                        .HasName("pk_vendor_transactions");

                    b.HasIndex("VendorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vendor_transactions_vendor_id_occurred_at");

                    b.HasIndex("VendorId", "VendorReference")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_transactions_idempotency");

                    b.HasIndex("BrandId", "PlayerId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_vendor_transactions_player_timeline");

                    b.ToTable("vendor_transactions", "ingest");
                });
#pragma warning restore 612, 618
        }
    }
}
