#!/usr/bin/env bash
# Provisions the ZITADEL instance for the PAM POC.
#
# Reads the bootstrap PAT that ZITADEL writes to the shared volume on first
# init, then creates two Orgs (one per Brand) and a Project + API audience
# the Pam.Api validates JWTs against. Writes resulting IDs and the admin PAT
# to .env.zitadel for the API host to consume.
#
# Idempotent: re-running this finds existing Orgs/Project by name and skips.
#
# Usage: ./infra/zitadel/bootstrap.sh

set -euo pipefail

ZITADEL_URL="${ZITADEL_URL:-http://localhost:8080}"
PAT_FILE="${PAT_FILE:-/var/lib/docker/volumes/pam_pam-zitadel-machinekey/_data/zitadel-admin-sa.pat}"
ENV_OUT="${ENV_OUT:-./.env.zitadel}"

PROJECT_NAME="${PROJECT_NAME:-pam-player-api}"
AUDIENCE="${AUDIENCE:-pam-player-api}"

BRAND_EU_ORG="${BRAND_EU_ORG:-betanything-eu}"
BRAND_LATAM_ORG="${BRAND_LATAM_ORG:-betanything-latam-stub}"

# --- read PAT (try docker volume path, then docker cp, then a host-mount fallback) ---
if [[ ! -f "$PAT_FILE" ]]; then
  if command -v docker >/dev/null 2>&1; then
    echo "PAT not at $PAT_FILE — pulling from container volume..."
    docker cp pam-zitadel:/machinekey/zitadel-admin-sa.pat ./infra/zitadel/.zitadel-admin-sa.pat
    PAT_FILE="$(pwd)/infra/zitadel/.zitadel-admin-sa.pat"
  fi
fi

if [[ ! -f "$PAT_FILE" ]]; then
  echo "ERROR: cannot find ZITADEL admin PAT at $PAT_FILE" >&2
  exit 1
fi

PAT="$(tr -d '[:space:]' < "$PAT_FILE")"
if [[ -z "$PAT" ]]; then
  echo "ERROR: PAT file is empty" >&2
  exit 1
fi

auth=(-H "Authorization: Bearer $PAT" -H "Content-Type: application/json")

# --- helpers ---
find_org_id() {
  local name="$1"
  curl -fsS -X POST "$ZITADEL_URL/management/v1/orgs/_search" \
    "${auth[@]}" \
    -d "{\"queries\":[{\"nameQuery\":{\"name\":\"$name\",\"method\":\"TEXT_QUERY_METHOD_EQUALS\"}}]}" \
    | python3 -c "import sys,json; r=json.load(sys.stdin); print(r['result'][0]['id'] if r.get('result') else '')"
}

create_org() {
  local name="$1"
  local existing
  existing="$(find_org_id "$name" || true)"
  if [[ -n "$existing" ]]; then
    echo "Org '$name' exists: $existing" >&2
    echo "$existing"
    return
  fi
  curl -fsS -X POST "$ZITADEL_URL/management/v1/orgs" \
    "${auth[@]}" \
    -d "{\"name\":\"$name\"}" \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])"
}

find_project_id() {
  local org_id="$1"
  local name="$2"
  curl -fsS -X POST "$ZITADEL_URL/management/v1/projects/_search" \
    "${auth[@]}" \
    -H "x-zitadel-orgid: $org_id" \
    -d "{\"queries\":[{\"nameQuery\":{\"name\":\"$name\",\"method\":\"TEXT_QUERY_METHOD_EQUALS\"}}]}" \
    | python3 -c "import sys,json; r=json.load(sys.stdin); print(r['result'][0]['id'] if r.get('result') else '')"
}

create_project() {
  local org_id="$1"
  local name="$2"
  local existing
  existing="$(find_project_id "$org_id" "$name" || true)"
  if [[ -n "$existing" ]]; then
    echo "Project '$name' exists in org $org_id: $existing" >&2
    echo "$existing"
    return
  fi
  curl -fsS -X POST "$ZITADEL_URL/management/v1/projects" \
    "${auth[@]}" \
    -H "x-zitadel-orgid: $org_id" \
    -d "{\"name\":\"$name\"}" \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])"
}

# --- run ---
echo "==> Bootstrapping ZITADEL at $ZITADEL_URL"

EU_ORG_ID="$(create_org "$BRAND_EU_ORG")"
LATAM_ORG_ID="$(create_org "$BRAND_LATAM_ORG")"

# The project lives in the EU Org; LATAM Org is granted access (added in a
# follow-up when the LATAM brand is real). For the POC, only EU plays the
# audience role.
PROJECT_ID="$(create_project "$EU_ORG_ID" "$PROJECT_NAME")"

cat > "$ENV_OUT" <<EOF
# Generated by infra/zitadel/bootstrap.sh — do not edit by hand.
ZITADEL_AUTHORITY=$ZITADEL_URL
ZITADEL_ADMIN_PAT=$PAT
ZITADEL_PROJECT_ID=$PROJECT_ID
ZITADEL_AUDIENCE=$AUDIENCE
ZITADEL_ORG_BETANYTHING_EU=$EU_ORG_ID
ZITADEL_ORG_BETANYTHING_LATAM_STUB=$LATAM_ORG_ID
EOF

echo "==> Wrote $ENV_OUT"
echo "    EU Org:    $EU_ORG_ID"
echo "    LATAM Org: $LATAM_ORG_ID"
echo "    Project:   $PROJECT_ID"
echo
echo "Set the following in appsettings.Development.json or as env vars before"
echo "running the API:"
echo "  Zitadel__AdminPat=\"$PAT\""
echo "  Brands__Map__betanything-eu__ZitadelOrgId=\"$EU_ORG_ID\""
echo "  Brands__Map__betanything-latam-stub__ZitadelOrgId=\"$LATAM_ORG_ID\""
