using Carter;
using MediatR;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace Pam.Identity.Authentication.Mfa;

// POST /v1/identity/me/mfa/verify { code }
public sealed class MfaVerifyEndpoint : ICarterModule
{
    public void AddRoutes(IEndpointRouteBuilder app)
    {
        app.MapPost(
                "/v1/identity/me/mfa/verify",
                async (MfaVerifyCommand command, ISender sender, CancellationToken ct) =>
                {
                    await sender.Send(command, ct);
                    return Results.NoContent();
                }
            )
            .WithTags("Identity")
            .WithName("MfaVerify")
            .WithSummary("Verify a TOTP code and finish MFA enrollment")
            .WithDescription(
                """
                Second step of MFA enrollment. Verifies the supplied `code`
                against the shared key generated by
                `/v1/identity/me/mfa/enroll`. On success two-factor is enabled
                on the account.

                **Auth:** any authenticated back-office user. Rate-limited by
                the `auth-sensitive` policy.

                **Idempotency:** once two-factor is enabled, subsequent calls
                are effectively no-ops (the same code can't be replayed because
                TOTP codes rotate every 30s).

                **Side effects:** sets `TwoFactorEnabled = true` on the user.
                Recovery codes are NOT auto-generated; the SPA should follow up
                with `POST /v1/identity/me/mfa/recovery-codes`.

                **Status codes:**
                - `204 No Content` — code verified; MFA now enabled.
                - `400 Bad Request` — malformed body.
                - `401 Unauthorized` — not signed in.
                - `422 Unprocessable Entity` — code invalid or no shared key
                  on file (enrollment was never started).
                - `429 Too Many Requests` — rate-limited.
                """
            )
            .Produces(StatusCodes.Status204NoContent)
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status401Unauthorized)
            .ProducesProblem(StatusCodes.Status422UnprocessableEntity)
            .RequireAuthorization()
            .RequireRateLimiting("auth-sensitive");
    }
}
